# Generated by Django 4.0.4 on 2022-05-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcar',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='IdU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdUs', to='users.user'),
        ),
        migrations.AlterField(
            model_name='ratingcar',
            name='idd',
            field=models.ForeignKey(blank=True, db_column='IdD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdDs', to='users.user'),
        ),
    ]
