# Generated by Django 4.0.4 on 2022-06-02 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='idd',
            field=models.ForeignKey(blank=True, db_column='IdD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdDr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='idU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdUr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingdriver',
            name='idd',
            field=models.ForeignKey(blank=True, db_column='IdD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingdriver',
            name='idr',
            field=models.ForeignKey(blank=True, db_column='IdR', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='ratingdriver',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='idU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdU', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingcar',
            name='idc',
            field=models.ForeignKey(blank=True, db_column='IdC', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car'),
        ),
        migrations.AddField(
            model_name='ratingcar',
            name='idd',
            field=models.ForeignKey(blank=True, db_column='IdD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdDs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingcar',
            name='idr',
            field=models.ForeignKey(blank=True, db_column='IdR', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='ratingcar',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='IdU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdUs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holding',
            name='idc',
            field=models.ForeignKey(db_column='IdC', on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car'),
        ),
    ]
