# Generated by Django 4.0.4 on 2022-06-02 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdriver',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='idU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdU', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='idU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdUr', to=settings.AUTH_USER_MODEL),
        ),
    ]
