# Generated by Django 4.0.4 on 2022-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_ratingcar_idu_alter_ratingcar_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcar',
            name='descr_djiler',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
