# Generated by Django 4.0.4 on 2022-06-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
