# Generated by Django 4.0.4 on 2022-06-02 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='idu',
            field=models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('idman', 'name')},
        ),
        migrations.AddField(
            model_name='car',
            name='idman',
            field=models.ForeignKey(blank=True, db_column='IdMan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdMan', to='cars.model'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, db_column='name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Model', to='cars.model'),
        ),
    ]
